# Generated by Django 4.0.4 on 2022-05-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0004_alter_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='fileType',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
