# Generated by Django 4.0.4 on 2022-05-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0005_board_filetype_alter_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
