# Generated by Django 4.0.4 on 2022-09-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0006_board_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='fileType',
        ),
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
        migrations.AddField(
            model_name='board',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
