# Generated by Django 3.2.15 on 2022-10-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0007_remove_board_filetype_remove_board_image_board_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='detect_files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
