# Generated by Django 4.1.2 on 2022-11-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0007_remove_board_filetype_remove_board_image_board_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
