# Generated by Django 3.2.15 on 2022-11-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_app', '0015_alter_board_detact_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
